@baseurl = http://localhost:3000

GET {{baseurl}}
###
GET {{baseurl}}/details

###
POST {{baseurl}}/details
Content-Type: application/json
Accept: application/json

{
    "token_ca": "0x6C4da7995555F85B6178138091CC513204b830a0"
}

###
POST {{baseurl}}/details
Accept: application/json
Content-Type: application/json

{
    "owner_address": "0x2d21cc84599156a8068d7a5b060339acdf17a176"
}
###
POST {{baseurl}}/details
Accept: application/json
Content-Type: application/json

{
    "approve_amount": "10"
}

###

POST {{baseurl}}/details
Accept: application/json
Content-Type: application/json

{
    "receiving_address": "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
}