@baseurl = http://localhost:3000

GET {{baseurl}}
###
GET {{baseurl}}/details
###
POST {{baseurl}}/details
Content-Type: application/json
Accept: application/json

{
    "token_ca": "0x6C4da7995555F85B6178138091CC513204b830a0"
}

###
POST {{baseurl}}/owner-address
Accept: application/json
Content-Type: application/json

{
    "owner_address": "owneraddress"
}